version: 2

sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - extra-pubkey-algs
        - xmp
        - opentype
        - image-support
        - pkcs11
        - async-http
formats: all
