version: 2

sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-latest
  tools:
    python: "3.13"
python:
  install:
    - method: pip
      path: pkgs/pyhanko
      extra_requirements:
        - docs
        - extra-pubkey-algs
        - opentype
        - image-support
        - pkcs11
        - async-http
formats: all
