name: "Test job setup"
description: "Init logic for pyHanko tests"
runs:
  using: "composite"
  steps:
    - name: Disable Python problem matchers
      shell: bash
      # we remove setup-python's problem matchers because
      # they aren't really an asset given the way pyHanko is tested
      run: echo "::remove-matcher owner=python::"
    - name: Install build deps
      shell: bash
      run: pip install --upgrade uv && uv venv
