name: Smoke tests for missing optional deps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build and test tools
        run: |
          python -m pip install --upgrade pip build
          pip install 'certomancer[web-api,pkcs12]~=0.9.0' 'pytest>=6.1.1' \
               requests-mock~=1.8.0 freezegun~=1.1.0 pytest-asyncio==0.19.0
      - name: Build and install library and basic dependencies
        run: |
          python -m build
          python -m pip install dist/*.whl
      - name: Run basic tests
        run: |
          python -m pytest \
            pyhanko_tests/test_signing.py pyhanko_tests/test_diff_analysis.py pyhanko_tests/test_crypt.py \
            pyhanko_tests/test_cms.py
