name: Static analysis

on: ["push", "pull_request"]

permissions:
  actions: read
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - run: pip install --upgrade uv
      - name: Check formatting
        run: uv run --group lint ruff format --check --diff
      - name: Check linting rules
        run: uv run --group lint ruff check
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - run: pip install --upgrade uv
      - run: uv run --all-packages --all-extras --group mypy mypy
